spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/todo-hexag
  mail:
    host: smtp.gmail.com
    port: 587
    username: vtsoliveira2001@gmail.com
    password: afrpwsxmpglewojd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          socketFactory:
            port: 46
            class: javax.net.ssl.SSLSocketFactory

security:
  jwtKey: '8BBZT6bKjUxRyLyf*y8u=Q7h94v*GSNA+NCZ#$Z^c-vTaGZ3Jm+$funuELg-922@he9cqFK4+PS#b#USpDXbTWYets7*=VbtLtA5_6VU#mJKDwL3DT^g%k-HvKrQ@c5#'